const imageSlider=[
    {
        id:1,
        image:"../../../../../public/imags/destinationCarousel/1.jpg"
    },
    {
        id:2,
        image:"../../../../../public/imags/destinationCarousel/2.jpg"
    },
    {
        id:3,
        image:"../../../../../public/imags/destinationCarousel/3.jpg"
    },
    {
        id:4,
        image:"../../../../../public/imags/destinationCarousel/4.jpg"
    },
    {
        id:5,
        image:"../../../../../public/imags/destinationCarousel/5.jpg"
    },
    {
        id:6,
        image:"../../../../../public/imags/destinationCarousel/6.jpg"
    },
    {
        id:7,
        image:"../../../../../public/imags/destinationCarousel/7.jpg"
    },
    {
        id:8,
        image:"../../../../../public/imags/destinationCarousel/8.jpg"
    },
    {
        id:9,
        image:"../../../../../public/imags/destinationCarousel/9.jpg"
    },
    {
        id:10,
        image:"../../../../../public/imags/destinationCarousel/10.jpg"
    },
]
export default imageSlider;