const imageSlider=[
    {
        id:1,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F1.jpg?alt=media"
    },
    {
        id:2,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F2.jpg?alt=media"
    },
    {
        id:3,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F3.jpg?alt=media"
    },
    {
        id:4,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F4.jpg?alt=media"
    },
    {
        id:5,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F5.jpg?alt=media"
    },
    {
        id:6,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F6.jpg?alt=media"
    },
    {
        id:7,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F7.jpg?alt=media"
    },
    {
        id:8,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F8.jpg?alt=media"
    },
    {
        id:9,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F9.jpg?alt=media"
    },
    {
        id:10,
        image:"https://firebasestorage.googleapis.com/v0/b/ghummakad-bad15.appspot.com/o/carousel%2F10.jpg?alt=media"
    },
]
export default imageSlider;